### ISSUE TITLE
can not install paper machine with latest Zotero 4.0.29.5 on Mac OS X EI Capitan 10.11 

### ISSUE THREAD

**Issue by aucu** [papermachines/papermachines#68]
Excuse me.
I tried many times, but it still does not work. I went to http://papermachines.org/install/    and  downloaded the latest version of Paper Machines 0.4.9.
But it can not be installed. Could you help me to solve this problem?

Thanks a lot!

**Comment by corajr** [comment]
Apologies; the version on that page is actually outdated. Please see issue #69 for the updated version.

**Comment by aucu** [comment]
Thanks Cora. I have added papermachine under your help.

Best regards.

2016-05-14 10:53 GMT-04:00 Cora Johnson-Roberson <notifications@github.com>:

> Apologies; the version on that page is actually outdated. Please see issue
> #69 <https://github.com/papermachines/papermachines/issues/69> for the
> updated version.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/papermachines/papermachines/issues/68#issuecomment-219224515>
>



-- 

Jintong Li
Ph.D.
Department of International Relations
Zhou Enlai School of Government
Nankai University,Tianjin,China
